name: Diffuse

on:
  pull_request:
    branches:
      - master
      - main
      - trunk
      - develop
      - maine
      - mane

jobs:
  run-diffuse:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: actions/cache@v4
        name: Download base
        with:
          path: |
            diffuse-source-file-release
          key: diffuse-${{ github.event.pull_request.base.sha }}
          restore-keys: diffuse-${{ github.event.pull_request.base.sha }}

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew assembleRelease

      - id: diffuse
        uses: usefulness/diffuse-action@master
        with:
          old-file-path: diffuse-source-file-release
          new-file-path: screenshot-testing-core/build/outputs/aar/screenshot-testing-core-release.aar

      - uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Diffuse output

      - uses: peter-evans/create-or-update-comment@v4
        if: ${{ steps.diffuse.outputs.diff-gh-comment != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            ### Apk size:
            Aar size change: ${{ steps.diffuse.outputs.size-diff-comment_style_1 }}

            ### Diffuse output:

            ${{ steps.diffuse.outputs.diff-gh-comment }}
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: diffuse-output
          path: ${{ steps.diffuse.outputs.diff-file }}
